chimecms/chime

chef/bizarro/recipes/default.rb, chef/bizarro/recipes/honcho-env, chef/repository/recipes/default.rb, setup-script.py
Correctly configure domain name of EC2 instance on setup, and use full domain name to populate `BROWSERID_URL` in chef scripts.
Closes #74.
=> Use working domain name for Persona API

.env.sample, Procfile, bizarro/__init__.py, bizarro/google_access_token_update.py, bizarro/google_api_functions.py, bizarro/views.py, bizarro/wsgi.py, run.py, test/test.py
Removed most uses of `os.environ` for config variables, added [`bizarro.create_app()` factory function](http://flask.pocoo.org/docs/0.10/patterns/appfactories/), added [Flask Blueprint support](http://flask.pocoo.org/docs/0.10/blueprints/), and made initial setup fail catastrophically when required variables are missing.
Closes #108.
=> Improved testability with app instance and os.environ

bizarro/__init__.py, bizarro/publish/__init__.py, bizarro/publish/functions.py, bizarro/views.py, env.sample
Made possible to configure `PUBLISH_SERVICE_URL` for a remote location to receive publication notifications, but have not implemented it yet.
Closes #43, leads to #163.
=> Separate publish service

.gitignore, bizarro/repo_functions.py, bizarro/view_functions.py, bizarro/views.py, test/test.py
+ Added a `@branch_required` decorator to ensure that you can't create branches by just navigating to them (see old screencap)
+ Cleaned up some rogue whitespace
+ Fixes #147 
+ Right now the implementation just redirects you back to `/`, but it might be nice to do a redirect-back. I'm not totally sure how to implement that though.
+ Are we doing flashes? If so, this should probably flash some sort of message.
**Old**
**New**
=> created branch_required decorator to enforce new branches with post only

chime/edit_functions.py, chime/repo_functions.py, chime/templates/articles-list.html, chime/templates/tree-branch-edit-listdir.html, chime/view_functions.py, chime/views.py, test/test.py
Added support for navigating the site with columns
* *category* dirs can be created
* *category* dirs contain an index file with *category* layout in front matter
* a `dir_columns` list is available to templates; see articles-list.html for sample display
* improved support for *article* dirs
* improved support for dirs and files that are not *articles* or *categories*
Closes #216
=> Enforce category site structure #216

chime/chimelog.py, chime/view_functions.py, test/test_chimelog.py
This adds some basic request info to the production system error alerts. The actual information added is pretty small now; this change is mainly intended to create a place to easily add things to the reports as we realize what we really need to run down production errors.
=> Production alerts now include some request details.

chime/templates/article-edit.html
fixes #239. Instead of a form that posts to /authorize, makes the google analytics button just redirect to the /setup page so users can actually configure the google analytics.
cc @phae
=> redirect google analytics button on edit page to setup screen

chime/edit_functions.py, chime/repo_functions.py, chime/view_functions.py, chime/views.py, test/unit/test.py
This hopefully fixes our blowy-uppy behavior when people try to create things that already exist.
It also creates a ChimeRepo object and moves some file-related code into it, hopefully improving clarity.
=> Fix failure on duplicate category or article creation

chime/templates/article-edit.html, chime/views.py, test/unit/test.py
values for order and description are:
* read from article or category front matter
* sent to the article-edit template
* rendered on the article-edit page in hidden form fields
* expected on article or category save and stored in front matter
part of #244 and #183 but doesn't close either.
=> Add order and description to front matter

chime/view_functions.py, chime/views.py, test/unit/test.py
Fixes a bug where deleting activities that hadn't been viewed or edited by you errored
* wrote a test to expose the bug
* required a synched checkout on /update
* updated synched_checkout_required() to check request.form for branch name
Closes #293
=> Delete unpulled activities #293

Procfile, chime/google_access_token_update.py, chime/google_api_functions.py, chime/worker.py
As part of #287, added a new `worker` process and moved GA token exchange there. Keeping the old `gapi_access_token ` process around as a no-op because Honcho doesn’t understand how to remove existing entries, only add and replace.
=> Added worker process

chime/__init__.py, chime/repo_functions.py, chime/view_functions.py, chime/worker.py, test/unit/test.py
If there is a remote origin defined on the app `REPO_PATH` (e.g. Github, or some permanent directory) then push to it asynchronously when changes are made.
Closes #287.
=> Add git backup sync daemon

chime/view_functions.py, chime/views.py, test/unit/chime_test_client.py, test/unit/test.py
Split functionality in update_activity_review_status into two parts:
* One part checks to make sure the update is authorized
* The second part actually performs the update
With that change, I can check to make sure someone's authorized to publish, attempt to publish, and then, update the activity's status to 'published' only if there was no error.
Closes #353
=> Fix conflicted activities marked published #353

chime/static/javascript/markdown-previewer.js
fixes #443 
I created a suite of markdown syntax errors I'm seeing in our bootcamp sites and tested live preview against the jekyll site preview.
Seems like turning off github-flavored markdown in the live preview fixes all of the discrepancies I can find so far.
@tmaybe mind taking a look at this?
_____________________________________
_____________________________________
_____________________________________
=> turning off git-flavored markdown for live preview

chime/repo_functions.py, chime/view_functions.py, jekyll/README.md, test/unit/chime_test_client.py, test/unit/test.py
Trying to navigate to branches that once existed but were published or deleted *and* also no longer exist locally will raise a 404 instead of a 500. Same with branches that never existed.
Closes #446
=> Raise 404 for missing branch

chime/chimelog.py, chime/view_functions.py, test/unit/test_logs.py
Gives a hopefully more useful production error report. Because broken error handlers are worse than no error handlers, the code tries very hard not to make things worse.
=> Add more detail to production error reports.

chime/templates/base.html, chime/templates/macros/macros.html, chime/templates/signin.html, chime/views.py, test/unit/app.py, test/unit/chime_test_client.py
Fixes the broken `Sign Out` button that is rendered when you're not authorized to access the site
Makes the methods and tests surrounding sign-in more consistent
Closes #406
=> Fix broken sign out button

chime/repo_functions.py, chime/templates/activity-overview.html, chime/templates/article-edit.html, test/unit/process.py
You can now browse a published branch if you've got a local copy of it in your repository.
Closes #456 
Also, the activity overview now shows a complete history in this state, including commits representing approval and publish, partially addressing #441. This is probably a side effect of a previous commit.
=> Make published branches browsable

chime/views.py, test/unit/app.py
fixes i/o 500 errors that were being raised when adding garbage text to the end of `/edit/` URLs.
Closes #355
=> Fix io error

.travis.yml, fabfile/fabconf.py, fabfile/requirements.txt, fabfile/tasks.py, test/acceptance/test_preview.py
Acceptance tests now upload data [to S3 in a publicly-accessible JSON file](http://chimecms-test-results.s3.amazonaws.com/acceptance-test-nights.json).
Sample data:
```JSON
[
{
"start": 1440721931.888421
}, 
{
"status": "done", 
"browser": "Windows 7 IE 9.0", 
"ok": true, 
"elapsed": 120.39418697357178
}, 
{
"status": "errored", 
"browser": "Windows 8.1 Firefox 35.0", 
"exception": "(<class 'selenium.common.exceptions.NoSuchElementException'>, NoSuchElementException(), <traceback object at 0x7fef36cd8488>)", 
"ok": false, 
"elapsed": 123.96230697631836
}, 
{
"status": "failed", 
"browser": "Windows 7 IE 8.0", 
"exception": "(<type 'exceptions.AssertionError'>, AssertionError('\\'You deleted\\' not found in u\"Saved changes to the article-916104 article! Remember to submit this change for …
```
=> Configure acceptance tests for nightly runs

.travis.yml
During September, we have an expanded suite of Browserstack tests running twice-daily. This PR removes Browserstack from the CI loop for that time.
=> Turned off Browserstack in Travis config

chime/jekyll_functions.py, chime/view_functions.py, jekyll/Gemfile.lock, test/unit/test_logs.py
Currently our tests are pretty noisy. Unless there are actual errors, I'd rather see a soothing row of dots. This gets everything but two bits of jibber-jabber coming from down in a publishing call somewhere.
=> suppressing some useless test output

chime/views.py, test/unit/app.py
Now that the task description entry form has a text area you can submit task descriptions with all kinds of crazy whitespace. This strips all excessive whitespace from submitted task descriptions.
=> Strip whitespace from task description

.gitignore, chime/chime_activity.py, chime/static/images/chime_symbol.svg, chime/static/javascript/activities-list.js, chime/static/sass/components/_activity-progress.scss, chime/static/sass/components/_buttons.scss, chime/static/sass/components/_modal.scss, chime/static/sass/components/_tooltip.scss, chime/static/sass/core/_animations.scss, chime/static/sass/core/_utilities.scss, chime/static/sass/main.scss, chime/static/sass/templates/_activities-list.scss, chime/static/sass/templates/_activity-overview.scss, chime/static/stylesheets/main.css, chime/static/stylesheets/styleguide.css, chime/templates/activities-list.html, chime/templates/activity-overview.html, chime/view_functions.py, chime/views.py, test/acceptance/test_preview.py, test/unit/app.py, test/unit/chime_test_client.py, test/unit/process.py
This pull request changes the layout of the activity dashboard view to:
1. Group activities by state so its easier to see what work is going on across the site and makes activity cards smaller so you can see more activities at once.
2. Add an activity action toolbar to each activity card so you can easily jump to either the content or the overview page.
3. Changes the link in the activity title to go to the overview page instead (allows us to not have an activity toolbar in the published activities and also it makes more sense for clicking on an activity to jump you the overview of the activity)
4. Puts the activity creation in a modal (better fits the interface and provides a space where we can provide a more in depth description of what an activity is)
@tmaybe can you review this?
=> Group activities by status #517

chime/storage/user_task.py, chime/views.py, test/unit/app.py
UserTask checks to see if a repo's dirty before it tries to commit it, and returns a boolean indicating whether it committed or not.
closes #539
=> Save unchanged content

.gitignore, chime/chime_activity.py, chime/repo_functions.py, chime/templates/activity-overview.html, chime/templates/base.html, chime/templates/macros/macros.html, chime/view_functions.py, chime/views.py, test/unit/app.py, test/unit/chime_test_client.py, test/unit/process.py, test/unit/repo.py, test/unit/test_logs.py
Accurately displays the histories of published activities on their overview pages.
I created a ChimePublishedActivity class, a sub-class of ChimeActivity that collects and parses its history differently.
I re-wrote how commits are structured so that Chime could easily find only the commits related to a specific merged branch. It's also backwards-compatible with the old style of commit.
And I re-wrote and -factored a bunch of code and tests to account for these changes.
=> Show published activities overview

chime/storage/user_task.py
Some tests (`test_notified_when_saving_article_in_published_activity` and `test_published_branch_not_resurrected_on_save`) were failing because UserTask was reporting the wrong author and date for published tasks. I fixed it by explicitly setting `self.commit_sha` to the hexsha of the tagged publish commit.
=> commit_sha in a published UserTask points to the publish commit
