chimecms/chime

bizarro/views.py, chef/account/recipes/default.rb, chef/repository/recipes/default.rb, requirements.txt, setup-script.py
Closes #84 by re-creating deploy key with basic auth.
=> Fix disappearing deploy keys

bizarro/view_functions.py
=> Added start of first commit SHA to repo dirname

bizarro/view_functions.py
=> Replaced `git push` with `git push --all` in synch* view decorators

bizarro/__init__.py, bizarro/google_access_token_update.py, bizarro/view_functions.py, bizarro/views.py
=> Switch to logging

.env.sample, README.md, bizarro/setup/functions.py, bizarro/setup/user-data.sh, chef/bizarro/recipes/default.rb, env.sample, setup-script.py
Moved necessary configuration information into setup scripts, including URL of authorization CSV.
Closes #118.
=> Make authentication spreadsheet readable

bizarro/__init__.py, bizarro/setup/functions.py, bizarro/setup/user-data.sh, bizarro/view_functions.py, bizarro/views.py, chef/account/recipes/default.rb, chef/bizarro/recipes/default.rb, chef/repository/recipes/default.rb, setup-script.py, test/test.py
Also tweaked spreadsheet URL and Github tokens passed to setup scripts.
Closes #126.
=> Saving deployed instance details

bizarro/google_access_token_update.py, bizarro/google_api_functions.py, bizarro/templates/authorization-complete.html, bizarro/templates/authorize.html, bizarro/templates/tree-branch-edit-file.html, bizarro/views.py, test/test.py
adapted the dashboard google analytics setup to ceviche
closes #105
=> Improve analytics setup

bizarro/templates/tree-branch-edit-listdir.html, bizarro/view_functions.py, requirements.txt, test/test.py
I'm getting file modification dates from git logs, using them to generate natural-language descriptions of the time since a file's been modified (like "4 hours ago"), and displaying them in the file explorer.
closes #107
=> Show modification dates in file explorer

bizarro/view_functions.py, bizarro/views.py
Filtering out files and directories that match certain patterns. Add *?showallfiles=true* to the url to show the file list without the filter.
Closes #104
=> Filter file explorer display

bizarro/google_access_token_update.py, bizarro/google_api_functions.py, bizarro/views.py, test/test.py
Creating the google analytics config file if it doesn't exist; handling reading and writing malformed or unexpected data; test coverage.
closes  #132
=> Handle missing or malformed config file

bizarro/templates/tree-branch-edit-file.html, bizarro/templates/tree-branch-history.html, bizarro/view_functions.py, bizarro/views.py, ga_config.json
=> Add page audit log

bizarro/setup/functions.py, setup-script.py
Also moved tons of code from `setup-script` to `bizarro.setup.functions`.
Closes #127.
=> Configure deploy webhook #127

bizarro/static/style.css, bizarro/templates/base.html, bizarro/templates/tree-branch-edit-file.html, bizarro/views.py
Set up template and css to display messages sent using Flask's flash() method. Will put it to use when working on #151 
Closes #134
=> Setup message flashing for alerts

bizarro/__init__.py, bizarro/templates/base.html, bizarro/view_functions.py, bizarro/views.py, bizarro/wsgi.py, env.sample, run.py, test/test.py
Added link to working site in the presence of `LIVE_SITE_URL` config setting.
Part of #43.
=> Link to working site

bizarro/view_functions.py, bizarro/views.py, test/test.py
=> Redirect to browseridurl #170

bizarro/templates/tree-branch-edit-listdir.html, bizarro/view_functions.py, bizarro/views.py, test/test.py
Generates updated and created dates for tasks and displays them on the tree-branch-edit-listdir page.
Closes #211
=> Store task date created and updated #211

chime/google_api_functions.py, chime/repo_functions.py, chime/templates/base.html, chime/templates/tree-branch-edit-file.html, chime/templates/tree-branch-edit-listdir.html, chime/view_functions.py, chime/views.py, test/test.py
=> Create directories with indexes #218

.travis.yml, test/unit/test.py
This should substantially reduce our Travis queue time. It should also speed up our builds somewhat due to caching.
=> Run tests in travis container

chime/static/sass/templates/_activities-list.scss, chime/static/stylesheets/main.css, chime/templates/activities-list.html, chime/views.py
Removes continue button from activity item as well as some other associated changes we talked about:
1. Removed the word 'review' from language. Changed to "Submit changes for feedback"
2. Made it so only the last editor can see the "Submit changes for feedback" button.
3. Changed metadata from creator to last editor on item because it more accurately reflects the state of the activity
cc @tmaybe @phae
=> Remove continue button from activity

chime/edit_functions.py, chime/repo_functions.py, chime/templates/articles-list.html, chime/view_functions.py, chime/views.py, jekyll/Gemfile.lock, test/unit/test.py
using `git rm` to remove files instead of os.rmdir and os.remove
added placement-only delete icons next to files in articles list
Closes #243
=> Fix deleting files and folders #243

.gitignore, chime/repo_functions.py, chime/static/javascript/placeholders.min.js, chime/static/sass/components/_activity-log.scss, chime/static/sass/components/_comment.scss, chime/static/sass/templates/_activities-list.scss, chime/static/stylesheets/main.css, chime/templates/activities-list.html, chime/templates/activity-bar.html, chime/templates/activity-overview.html, chime/templates/article-edit.html, chime/templates/article-history.html, chime/templates/articles-list.html, chime/templates/base.html, chime/templates/macros/macros.html, chime/templates/merge-conflict.html, chime/view_functions.py, chime/views.py, notes.txt, test/acceptance/e2e.py, test/acceptance/test_preview.py, test/unit/test.py
re-implements the review process
* can request feedback, endorse, and publish from the overview page
* shows review status on activities list (index) page
* allows commenting and status update from drop-down form
* decent test coverage
closes #229
=> Implement review model #229

chime/repo_functions.py, chime/view_functions.py, jekyll/Gemfile.lock, test/unit/test.py
* Preserves newlines in comments
* New test coverage to confirm
Closes #300
=> Show newlines in comments

chime/templates/base.html
Added the team to the GA account to access the data, too. :)
=> Add GA snippet, fixes #306

chime/static/sass/templates/_articles-list.scss, chime/static/stylesheets/main.css, chime/templates/articles-list.html, chime/templates/directory-modify.html, test/unit/test.py
Added the delete button back in for articles in the article-list view.
I'm making a pull request but a couple of things that would probably be good to do either in this branch or another branch:
1. Write a test to make sure we always have the ability to delete articles.
2. Include a flash message confirming that the article was deleted.
3. (bonus!) In the flash message, include a link to undo the deletion.
@tmaybe
=> adding delete button to articles

chime/view_functions.py, setup.py, test/unit/test.py
I have added a new test, which simulates two users in conflict over a published activity. The test passes because it’s checking for a 500 response, so we’ll need to follow this up with a modified test and new behavior.
Relevant to #349.
=> Test for published task

test/unit/test.py
Tomas and I looked at this together, and decided that the performance is Good Enough™ on the Springfield site to not need an optimization.
However, this PR does introduce a new test which can be used to verify that synch works if/when we decide to optimize this behavior.
~~Closes~~ Partially addresses #287.
=> Added multi-user test to check branch synch

chime/errors.py, chime/templates/activity-overview.html, chime/view_functions.py, chime/views.py, test/unit/test.py
Writes summaries of category & article creation, edit, and delete to commit messages in json format
Added some new functionality to the ChimeTestClient to support new tests
Tests the messages for deletes
This PR makes progress towards #350, with work continuing in [this branch](https://github.com/chimecms/chime/tree/show-changed-files-in-overview-%23350).
=> Write json to commits

chime/repo_functions.py, chime/templates/activity-overview.html, chime/view_functions.py, chime/views.py, test/unit/test.py
Calculates and displays a summary of the changed files in an activity at the top of the Activity Overview page.
Closes #350
=> Show changed files in overview

test/unit/test.py
Moved path and soup inside `ChimeTestClient` and started treating it more like a simple browser with a session. Test verbosity is much reduced.
Closes #374.
=> Improve chime test client

chime/view_functions.py, test/unit/test.py
Fixed (sub-)category and article names cropping on period.
Closes #320
=> Period in name okay #320

chime/repo_functions.py, test/unit/test.py
Changed the way branch names are generated:
* name is now 9 characters long instead of 7
* name is randomly generated using consonants that aren't in hex numbers
Closes #340
=> New branch names

chime/repo_functions.py, test/unit/test.py
Tags the merge/publish commit with a tag with the same name as the branch, and the jsonified task metadata
Closes #378
=> Apply tag when publishing

chime/view_functions.py, test/unit/test.py
=> Added lifespan for cached auth checks

chime/templates/activities-list.html
=> added 'requested feedback' notice to activity list

.travis.yml, chime/__init__.py, chime/view_functions.py, test/unit/test.py
* ~~Fix underlying test repository? “Build Warning: Layout 'article' requested in hello/index.markdown does not exist.”~~
Closes #385.
=> Support PUBLISH_PATH

chime/views.py, test/unit/test.py
Requires a non-blank name for a new category or article
Also checks for names that slugify to blank names
Closes #327
=> Require category or article name

chime/repo_functions.py, chime/templates/activities-list.html, chime/view_functions.py, chime/views.py, test/unit/chime_test_client.py, test/unit/test.py
A description is now required to create a new activity
Closes #334
=> Require activity description

chime/worker.py
=> Made REPO_PATH optional for chime.worker

chime/__init__.py, chime/data/authentication.csv, chime/templates/signin.html, chime/view_functions.py, chime/views.py, env.sample, test/unit/test.py
I’ve added a primitive warning [in signin.html](https://github.com/chimecms/chime/blob/59bab8f97e27abdd6f253f0840ac9d65f5c6df13/chime/templates/signin.html#L20) and tested for it [in test.py](https://github.com/chimecms/chime/blob/59bab8f97e27abdd6f253f0840ac9d65f5c6df13/test/unit/test.py#L2403) but I’d like @tmaybe or @norrishung to make sure it looks like it should.
Closes #387 and closes #388.
=> Open up default auth to everyone, but warn about it.

chime/repo_functions.py, chime/view_functions.py, chime/views.py, test/unit/test.py
Refactored the flow of setting an activity's status and publishing/clobbering/abandoning a branch.
This makes progress toward #346
=> Refactor status and publish flow

chime/view_functions.py
=> using getattr for error code instead of try/except

chime/views.py, test/acceptance/test_preview.py, test/unit/chime_test_client.py, test/unit/test.py
If there's a single visible folder (that doesn't represent a category or article) in a directory, Chime will automatically redirect inside of that folder. Includes a test.
Closes #299
=> Auto open solo folders

chime/templates/base.html, chime/templates/macros/macros.html, test/unit/test.py
=> Fix visit site link

chime/view_functions.py, chime/views.py, test/unit/test.py
New flash messages when categories are created, and when articles are created, edited, or deleted.
Closes #431
=> Flash on create category

chime/repo_functions.py, chime/templates/activity-overview.html, chime/templates/article-edit.html, chime/templates/articles-list.html, chime/templates/directory-modify.html, chime/templates/macros/macros.html, chime/view_functions.py, chime/views.py, test/unit/chime_test_client.py, test/unit/test.py
Detects when working in a published or deleted task and
1. Flashes a notice to the user, and
2. Hides all form elements that'd allow the user to make changes
Closes #301 
Closes #337 
Closes #346 
Closes #347 
Closes #349
=> Check for published or deleted branch

chime/repo_functions.py, chime/view_functions.py, chime/views.py, test/unit/app.py, test/unit/chime_test_client.py, test/unit/process.py, test/unit/test.py
To do:
* ~~Clean up the unholy mess in [`view_functions.save_page()`](https://github.com/chimecms/chime/blob/d13361d5851bcaf448e84d32a7cf9b9721a65f20/chime/view_functions.py#L1293).~~
Will close #321.
=> [WIP] Fix save article error

test/unit/chime_test_client.py, test/unit/process.py
Added two tests to confirm that you can't recreate deleted and published branches by saving files in them.
Closes #348
=> No resurrected branch on save

chime/errors.py, chime/static/sass/components/_global-header.scss, chime/static/stylesheets/main.css, chime/templates/macros/macros.html, test/unit/app.py
Shows flask debug view when the application is in DEBUG mode.
Also shows a notice when you're running Chime in debug mode; passing to @norrishung to fix emoji styling in that notice.
Closes #419
=> Show flask debug view

README.md, chime/repo_functions.py, chime/view_functions.py, env.sample, requirements.txt
Upgraded GitPython to 1.0.1, made a few UTF-8 encoding changes throughout. [GitPython #325](https://github.com/gitpython-developers/GitPython/issues/325) suggests this might be enough. App and Process tests passed locally.
* ~~Get full test suite passing.~~
Closes #455?
=> Resolve GitPython stderr line count 

chime/error_functions.py, chime/errors.py, chime/templates/error_500.html, chime/view_functions.py
=> Added error UUID to SNS message and user-facing display

chime/chimelog.py
=> Added error ID to SNS data

chime/view_functions.py, chime/views.py, test/unit/app.py
Raises a 404 error when trying to load non-existent assets in preview mode.
Closes #458
=> Fix 500 error in preview

chime/static/javascript/markdown-bar.js, chime/static/sass/components/_dropdown-nav.scss, chime/static/sass/components/_global-header.scss, chime/static/sass/components/_markdown-bar.scss, chime/static/stylesheets/main.css, chime/templates/macros/macros.html
Fixes #484. Also fixes some minor layout issues in the activity dropdown.
@tmaybe. I can go through changes with you tomorrow if you'd like.
=> Fixing markdown bar behavior

chime/view_functions.py, test/acceptance/test_preview.py, test/unit/chime_test_client.py, test/unit/process.py
Fixes the unrecoverable error and makes it a very bad error instead – the person saving now loses their work and is alerted that this has happened. I'll start a new issue about resolving the conflict gracefully.
Closes #474
=> Fix unrecoverable error on edit #474

chime/jekyll_functions.py, chime/repo_functions.py, chime/view_functions.py, chime/views.py, fabfile/tasks.py, requirements.txt, test/unit/app.py
Reprise of #481, possibly closes #455.
=> Upgraded GitPython to 1.0.1

chime/templates/activities-list.html, chime/view_functions.py, test/acceptance/test_preview.py, test/unit/app.py, test/unit/chime_test_client.py
The 10 most recently published activities are now shown on the front page. You can't click into them. This is the first stage of addressing #519 as described [in this comment](https://github.com/chimecms/chime/issues/519#issuecomment-138688904).
=> Show published activities in list

chime/chime_activity.py, chime/constants.py, chime/error_functions.py, chime/repo_functions.py, chime/view_functions.py, chime/views.py, test/unit/app.py, test/unit/repo.py, test/unit/test.py
I created a ChimeActivity class for managing activities in the application. This PR replaces every place we were creating an independent activity object with an instantiation of the class.
Part of the work towards completing #519
=> Introduce ChimeActivity class

chime/view_functions.py
Fixes the duplicate selection bug in the articles list.
Closes #541
=> Fix highlight bug on articles list

chime/chime_activity.py
I made a `BaseActivity` superclass for the `ChimeActivity` and `ChimePublishedActivity` classes to reduce duplication.
=> made a superclass for activities to inherit from
